[profile.default]
solc_version = "0.8.26"
evm_version = "shanghai"
auto_detect_solc = false
optimizer = true
optimizer_runs = 800 # fails at 1_000 because certain contracts become too large
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 1
via_ir = false
remappings = [
    '/=src',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'forge-deploy/=lib/forge-deploy/contracts',
    "@layerzerolabs/lz-evm-oapp-v2/=lib/layerzerolabs/lz-evm-oapp-v2/package",
    "@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzerolabs/lz-evm-messagelib-v2/package",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzerolabs/lz-evm-protocol-v2/package",
    "@openzeppelin/=lib/openzeppelin/",
    "openzeppelin-contracts/=lib/openzeppelin/contracts",
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    'solady/=lib/solady/src/',
    'mixins/=src/mixins',
    'solmate/=lib/solmate/src/'
]
auto_detect_remappings = false
match-path = "test/**/*.t.sol"
match-contract = "Test$"
ffi = false
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
    { access = "read", path = "./config" },
]

[profile.ci]
verbosity = 4

[profile.ci.fuzz]
verbosity = 4
runs = 256

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
fail_on_revert = true
# See more config options https://book.getfoundry.sh/reference/config/
